# Aprendizado não-supervisionado: Atividade 2

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import math 

In [2]:
from numpy import *

## Questão 1

### a) Matriz de usuários por filme

In [3]:
data = {'Romance': [0.9,0.8,0.3,0.6,0], 'Action': [0.1,0.2,0.7,0.4,1]}  
user_feature_matrix = pd.DataFrame(data)
user_feature_matrix = user_feature_matrix.rename(index={0: "User A", 1: "User B",2:"User C",3:"User D",4:"User E"})
user_feature_matrix

Romance  Action
User A      0.9     0.1
User B      0.8     0.2
User C      0.3     0.7
User D      0.6     0.4
User E      0.0     1.0

In [4]:
data2 = {'Romance': [0.9,0.1,0.5,0,0.2], 'Action': [0.1,0.9,0.5,1,0.8]}  
movie_feature_matrix = pd.DataFrame(data2)
movie_feature_matrix = movie_feature_matrix.rename(index={0: "Titanic", 1: "Rocky",2:"The Hobbit",3:"Fight Club",4:"Jurassic Park"})
movie_feature_matrix

Romance  Action
Titanic            0.9     0.1
Rocky              0.1     0.9
The Hobbit         0.5     0.5
Fight Club         0.0     1.0
Jurassic Park      0.2     0.8

In [5]:
movie_feature_matrix_t = movie_feature_matrix.transpose()
movie_feature_matrix_t

Titanic  Rocky  The Hobbit  Fight Club  Jurassic Park
Romance      0.9    0.1         0.5         0.0            0.2
Action       0.1    0.9         0.5         1.0            0.8

In [6]:
gostos = np.dot(user_feature_matrix,movie_feature_matrix_t)
gostos_matrix = pd.DataFrame(gostos)
gostos_matrix = gostos_matrix.rename(index={0: "User A", 1: "User B",2:"User C",3:"User D",4:"User E"})
gostos_matrix.columns = ["Titanic", "Rocky","The Hobbit","Fight Club","Jurassic Park"]
gostos_matrix

Titanic  Rocky  The Hobbit  Fight Club  Jurassic Park
User A     0.82   0.18         0.5         0.1           0.26
User B     0.74   0.26         0.5         0.2           0.32
User C     0.34   0.66         0.5         0.7           0.62
User D     0.58   0.42         0.5         0.4           0.44
User E     0.10   0.90         0.5         1.0           0.80

### b) Os dois usuários mais parecidos

A menor distância euclidiana é entre os usuários A e B, a maior é entre os usuários A e E.

In [7]:
def numero_atributos(dados):
  return dados.shape[0]

def erro(a,b):
  return a.values-b.values

In [8]:
matrix_erros = []
for i in range(0, 4):
    for j in range(0,4):
        if (i > j+1) == False:
            pass 
            matrix_erros.append(erro(gostos_matrix.iloc[i:i+1,], gostos_matrix.iloc[j+1:j+2,]))

matrix_erros

[array([[ 0.08, -0.08,  0.  , -0.1 , -0.06]]),
 array([[ 0.48, -0.48,  0.  , -0.6 , -0.36]]),
 array([[ 0.24, -0.24,  0.  , -0.3 , -0.18]]),
 array([[ 0.72, -0.72,  0.  , -0.9 , -0.54]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[ 0.4, -0.4,  0. , -0.5, -0.3]]),
 array([[ 0.16, -0.16,  0.  , -0.2 , -0.12]]),
 array([[ 0.64, -0.64,  0.  , -0.8 , -0.48]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[-0.24,  0.24,  0.  ,  0.3 ,  0.18]]),
 array([[ 0.24, -0.24,  0.  , -0.3 , -0.18]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[ 0.48, -0.48,  0.  , -0.6 , -0.36]])]

In [9]:
#Roubei a função dos arrays daqui:
#https://stackoverflow.com/questions/3157374/how-do-you-remove-a-numpy-array-from-a-list-of-numpy-arrays
def removearray(L,arr):
    ind = 0
    size = len(L)
    while ind != size and not np.array_equal(L[ind],arr):
        ind += 1
    if ind != size:
        L.pop(ind)
    else:
        raise ValueError('array not found in list.')

for i in range (0,3):
    removearray(matrix_erros,[[0., 0., 0., 0., 0.]])
    
matrix_erros

[array([[ 0.08, -0.08,  0.  , -0.1 , -0.06]]),
 array([[ 0.48, -0.48,  0.  , -0.6 , -0.36]]),
 array([[ 0.24, -0.24,  0.  , -0.3 , -0.18]]),
 array([[ 0.72, -0.72,  0.  , -0.9 , -0.54]]),
 array([[ 0.4, -0.4,  0. , -0.5, -0.3]]),
 array([[ 0.16, -0.16,  0.  , -0.2 , -0.12]]),
 array([[ 0.64, -0.64,  0.  , -0.8 , -0.48]]),
 array([[-0.24,  0.24,  0.  ,  0.3 ,  0.18]]),
 array([[ 0.24, -0.24,  0.  , -0.3 , -0.18]]),
 array([[ 0.48, -0.48,  0.  , -0.6 , -0.36]])]

In [10]:
df_erros = pd.DataFrame(np.concatenate(matrix_erros))
df_erros = df_erros.rename(index={0: "AB", 1: "AC",2:"AD",3:"AE",4:"BC",
                                 5:"BD",6:"BE",7:"CD",8:"CE",9:"DE"})
df_erros.columns = ["Titanic", "Rocky","The Hobbit","Fight Club","Jurassic Park"]
df_erros

Titanic  Rocky  The Hobbit  Fight Club  Jurassic Park
AB     0.08  -0.08         0.0        -0.1          -0.06
AC     0.48  -0.48         0.0        -0.6          -0.36
AD     0.24  -0.24         0.0        -0.3          -0.18
AE     0.72  -0.72         0.0        -0.9          -0.54
BC     0.40  -0.40         0.0        -0.5          -0.30
BD     0.16  -0.16         0.0        -0.2          -0.12
BE     0.64  -0.64         0.0        -0.8          -0.48
CD    -0.24   0.24         0.0         0.3           0.18
CE     0.24  -0.24         0.0        -0.3          -0.18
DE     0.48  -0.48         0.0        -0.6          -0.36

In [11]:
df_erros_list = df_erros.values.tolist()
df_erros_list = df_erros_list[0]
df_erros_list

[0.07999999999999996, -0.07999999999999999, 0.0, -0.1, -0.06000000000000005]

In [12]:
def tamanho_distancia_euclidiana(e):
  soma = 0
  for i in range(0, len(e)):
   soma = soma + e[i]**2
  return math.sqrt(soma)

In [13]:
 tamanho_distancia_euclidiana(df_erros_list)

0.16248076809271922

In [14]:
df_erros_list = df_erros.values.tolist()
df_dist = []
def n_distancia_euclidiana(df_erros_list):
    for i in range(0, 10):
            errors = df_erros_list[i]
            df_dist.append(tamanho_distancia_euclidiana(errors))

In [15]:
n_distancia_euclidiana(df_erros_list)
df_dist = pd.DataFrame(df_dist)
df_dist = df_dist.rename(index={0: "AB", 1: "AC",2:"AD",3:"AE",4:"BC",
                                 5:"BD",6:"BE",7:"CD",8:"CE",9:"DE"})
df_dist.columns = ["dist"]

In [16]:
#A menor distância euclidiana é entre os usuários A e B, a maior é entre os usuários A e E.
df_dist

dist
AB  0.162481
AC  0.974885
AD  0.487442
AE  1.462327
BC  0.812404
BD  0.324962
BE  1.299846
CD  0.487442
CE  0.487442
DE  0.974885

In [17]:
print(min(df_dist.dist),max(df_dist.dist))

0.16248076809271922 1.462326912834473


In [18]:
df_dist[df_dist.dist == 0.16248076809271922]

dist
AB  0.162481

In [19]:
df_dist[df_dist.dist == 1.462326912834473]

dist
AE  1.462327

## Questão 2

1. A similaridade de Jaccard é usada para medir similaridade entre conjuntos finitos e é definido como a cardinalidade da interseção entre dois cojuntos divididos pela cardinalidade da união desses conjuntos. $Jaccard Similarity \rightarrow J(A,B) = |A∩B|/|A∪B|$



2. Diferenças entre Similaridade de Jaccard e Similaridade de Cossenos:

    - A similaridade de Jaccard  recebe somente conjuntos de palavras únicas em cada sentença/documento, enquanto a similaridade de cossenos recebe o comprimento total dos vetores.

    - Isso significa que se você repetir uma palavra na frase 1 várias vezes, a similaridade de cossenos muda, mas a similaridade de Jaccard não. Por exemplo, a palavra "friend" é repetidade na primeira frase 50 vezes, a similaridade de cossenos é reduzida para 0.4, mas a similaridade de Jaccard se mantém 0.5.
    
    - A similaridade de Jaccard é boa para casos onde duplicação não faz diferença, similaridade de cossenos é boa para casos onde duplicação importa quando analizando a similaridade dos textos. Por exemplo, para duas descrição de um produto, seria melhor usar similaridade de Jaccard, uma vez que as repetições de palavras não reduzem sua similaridade.

Referências:
- https://towardsdatascience.com/overview-of-text-similarity-metrics-3397c4601f50
- https://medium.com/@ashukumar27/similarity-functions-in-python-aa6dfe721035

#### Código da aula

In [20]:
def numero_atributos(dados):
  return dados.shape[0]

In [21]:
df = pd.read_csv('https://raw.githubusercontent.com/MahnoorJaved98/Movie-Recommendation-System/main/movie_dataset.csv')

In [22]:
# Preenche campos vazios com uma string vazia
features = ['keywords', 'cast', 'genres', 'director']
for feature in features:
    df[feature] = df[feature].fillna('')

In [23]:
def combined_features(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
df["combined_features"] = df.apply(combined_features, axis =1)

In [24]:
### Funções que criamos anteriormente para medir similaridade
def tamanho_distancia_euclidiana(e):
  soma = 0
  for i in range(0, numero_atributos(e)):
   soma = soma + e[i]**2
  return sqrt(soma)

def similaridade(a,b):
  soma = 0
  for i in range(numero_atributos(a)):
    soma = soma + (a[i]*b[i])
  return soma

def similaridade_normalizada(a,b): #cosseno
    return similaridade(a,b)/(tamanho_distancia_euclidiana(a)*tamanho_distancia_euclidiana(b))

def similaridade_com_todos(A, b):
  todas_similaridades = zeros(numero_atributos(A))
  
  for i in range(numero_atributos(A)):
    todas_similaridades[i] = similaridade_normalizada(A[i, :], b)

  return todas_similaridades

def recomendar_por_similaridade(A, b):
  todas_similaridades = similaridade_com_todos(A, b)
  return argmax(todas_similaridades), max(todas_similaridades)

def similaridade_par_a_par(A):
  todas_similaridades = zeros((numero_atributos(A), numero_atributos(A)))
  for i in range(numero_atributos(A)):
    todas_similaridades[i,:] = similaridade_com_todos(A, A[i,:])
  return todas_similaridades

In [25]:
def get_index_from_title(title):
    return df[df.title == title]["index"].values[0]

def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]

In [26]:
def recupera_filmes_mais_similar(nome_do_filme, filmes_similar, top=10):
  # Recupera índice do filme dado o nome
  movie_index = get_index_from_title(nome_do_filme)
  
  # Recupera o vetor com a similaridade deste filme e todos os outros
  mais_similares = list(enumerate(filmes_similar[movie_index]))
  
  # Ordenando do mais similar (maior valor) para o menor (menor valor)
  # Lembrando que se fosse distância seria ao contrário!
  mais_similares_ordenado = sorted(mais_similares, key=lambda x:x[1], reverse=True)

  # Exibe os top-X
  for i in range(top+1):
    print(get_title_from_index(mais_similares_ordenado[i][0]), mais_similares_ordenado[i][1])

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
filmes_por_termos = cv.fit_transform(df["combined_features"])

In [28]:
### Calculando a similaridade entre filmes
from sklearn.metrics.pairwise import *
filmes_similar = cosine_similarity(filmes_por_termos)
filmes_similar_man = manhattan_distances(filmes_por_termos)
filmes_similar_eucl = euclidean_distances(filmes_por_termos)

In [29]:
#recupera_filmes_mais_similar("Forrest Gump", filmes_similar)
recupera_filmes_mais_similar("Dead Poets Society", filmes_similar)

Dead Poets Society 0.9999999999999993
Much Ado About Nothing 0.21677749238102995
Patch Adams 0.21052631578947364
Good Will Hunting 0.2051956704170308
Flightplan 0.19564639521780736
Alive 0.19134594929397594
The Basket 0.1908854288927333
What Just Happened 0.1873171623163388
Adulterers 0.18394180184548975
The Sting 0.1835325870964494
The Tree of Life 0.179968508266339


In [30]:
recupera_filmes_mais_similar("Dead Poets Society", filmes_similar_man)

The Inhabited Island 55.0
Spawn 50.0
What's Love Got to Do with It 50.0
Pirates of the Caribbean: At World's End 49.0
I Am Legend 49.0
The Matrix Reloaded 49.0
Treasure Planet 49.0
102 Dalmatians 49.0
Death Race 49.0
Thunderbirds 49.0
The Iron Giant 49.0


In [31]:
recupera_filmes_mais_similar("Dead Poets Society", filmes_similar_eucl)

Saving Private Ryan 8.06225774829855
The Inhabited Island 8.06225774829855
In the Land of Blood and Honey 8.0
Cold Mountain 7.937253933193772
Brothers 7.937253933193772
Ramona and Beezus 7.937253933193772
Operation Chromite 7.745966692414834
Tiny Furniture 7.745966692414834
Sweet Sweetback's Baadasssss Song 7.681145747868608
They Will Have to Kill Us First 7.615773105863909
The Monuments Men 7.54983443527075


In [32]:
 df.combined_features[df.title == "Dead Poets Society"].iloc[0]

'individual philosophy poetry shakespeare professor Robin Williams Ethan Hawke Robert Sean Leonard Gale Hansen Josh Charles Drama Peter Weir'

In [33]:
df.combined_features.values[0]

'culture clash future space war space colony society Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Action Adventure Fantasy Science Fiction James Cameron'

### a) Jaccard Similarity

Escolhi a similaridade de Jaccard por, como descrito anteriormente, ser eficiente para casos onde repetições de palavras não importam. Não consegui usar bem as funções dadas na aula 2, então escrevi algumas e peguei outras de sites que tratavam do assunto.

A primeira função 'jaccard_binary' encontra a similaridade entre dois vetores e a função 'jacc_binary' ajusta os 'combined_features' utilizando o CountVectorize() e aplica a primeira função ao conjunto de dados ajustado, retornando os 10 valores com a maior similaridade.

O rankeamento das similaridades foi bem parecido com a aplicação da similaridade de cosseno. Chama a atenção a presença de 'Robin and Marian' com a mesma similaridade de 'Good Will Hunting' para o caso da distribuição da similaridade de Jaccard, mas não aparecendo entre os 10 primeiros casos utilizando a similaridade de cosseno.

É interessante observar também que os valores das similaridades de Jaccard são inferiores aos valores das similaridades de cosseno.

####  Com tokenização.

In [34]:
def jaccard_binary(x,y):
    """A function for finding the similarity between two binary vectors"""
    intersection = np.logical_and(x, y)
    union = np.logical_or(x, y)
    similarity = intersection.sum() / float(union.sum())
    return similarity

In [35]:
def jacc_binary(nome_do_filme,df):
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(df["combined_features"])
    arr = X.toarray()
    datafilme = {'nome_do_filme': [], 'similaridade': []}
    filmes_lista = pd.DataFrame(datafilme)
    for i in range(0,4803):
        ind1 = df.index[df.title == nome_do_filme]
        ind2 = df.index[df.title == df.title.values[i]]
        sim = jaccard_binary(arr[ind1],arr[ind2])
        filmes_lista.loc[i] = [df.title.values[i],sim]
    return(filmes_lista.sort_values('similaridade',ascending=False).head(n=10))

In [36]:
jacc_binary("Dead Poets Society",df)

nome_do_filme  similaridade
2453      Dead Poets Society      1.000000
3250  Much Ado About Nothing      0.138889
905              Patch Adams      0.117647
3616        Robin and Marian      0.114286
2975       Good Will Hunting      0.114286
1774      What Just Happened      0.111111
825               Flightplan      0.108108
1507                   Alive      0.105263
1446        The Tree of Life      0.105263
4273              The Basket      0.103448

In [37]:
recupera_filmes_mais_similar("Dead Poets Society", filmes_similar)

Dead Poets Society 0.9999999999999993
Much Ado About Nothing 0.21677749238102995
Patch Adams 0.21052631578947364
Good Will Hunting 0.2051956704170308
Flightplan 0.19564639521780736
Alive 0.19134594929397594
The Basket 0.1908854288927333
What Just Happened 0.1873171623163388
Adulterers 0.18394180184548975
The Sting 0.1835325870964494
The Tree of Life 0.179968508266339


#### Extra: Sem tokenização.

Tentei aplicar a similaridade sem tokenização para ver o que acontece. Queria saber se, mesmo sem a tokenização, o rankeamento seria parecido ou apresentaria alguma ordenação que fizesse sentido com os resultados anteriores. Não foi nada parecido ('Howard the Duck' tem similaridade máxima com 'Dead Poets Society'). Tudo aqui é só um teste, não deve ser considerado. 

In [38]:
def jaccard_similarity(x,y):
 intersection_cardinality = len(set.intersection(*[set(x), set(y)]))
 union_cardinality = len(set.union(*[set(x), set(y)]))
 return intersection_cardinality/float(union_cardinality)

In [ ]:
def jaccard (nome_do_filme,df):
    datafilme = {'nome_do_filme': [], 'similaridade': []}
    filmes_lista = pd.DataFrame(datafilme)
    for i in range(0,4803):
        features_filme = df.combined_features.values[i]
        outro_filme = df.title.values[i]
        feat_do_filme = df.combined_features[df.title == nome_do_filme].iloc[0]
        jacc = jaccard_similarity(feat_do_filme,features_filme)
        filmes_lista.loc[i] = [outro_filme,jacc]
    return(filmes_lista.sort_values('similaridade',ascending=False).head(n=10))

In [ ]:
datafilme = {'nome_do_filme': [], 'similaridade': []}
uma_lista_qlqr = pd.DataFrame(datafilme)

features_filme = df.combined_features.values[825]
outro_filme = df.title.values[825]
feat_do_filme = df.combined_features[df.title == "Dead Poets Society"].iloc[0]
jacc = jaccard_similarity(feat_do_filme,features_filme)
uma_lista_qlqr.loc[1] = [outro_filme,jacc]
uma_lista_qlqr

In [ ]:
jaccard("Dead Poets Society",df)

In [ ]:
#.sort_values(by=['similaridade'],ascending=True).head(n=10)
datafilme = {'nome_do_filme': [], 'similaridade': []}
uma_lista_qlqr = pd.DataFrame(datafilme)
d2d3 = jaccard_similarity("Dead Poets Society","Much Ado About Nothing")
d2d4 = jaccard_similarity("Dead Poets Society","Josie and the Pussycats")

uma_lista_qlqr.loc[1] = ["Much Ado About Nothing",d2d3]
uma_lista_qlqr.loc[2] = ["Josie and the Pussycats",d2d4]
uma_lista_qlqr

In [ ]:
def jaccard_nomes (nome_do_filme,df):
    datafilme = {'nome_do_filme': [], 'similaridade': []}
    filmes_lista = pd.DataFrame(datafilme)
    for i in range(0,4803):
        #features_filme = df.combined_features.values[i]
        outro_filme = df.title.values[i]
        #feat_do_filme = df.combined_features[df.title == nome_do_filme].iloc[0]
        jacc = jaccard_similarity(nome_do_filme,outro_filme)
        filmes_lista.loc[i] = [outro_filme,jacc]
    return(filmes_lista.sort_values('similaridade',ascending=False).head(n=10))

In [ ]:
jaccard_nomes("Dead Poets Society",df)

### b) Recomendações

Tentei duas abordagens aqui: um filme comum e um de franquia. 

Para o primeiro caso escolhi 'Beavis and Butt-Head Do America'. Utilizando a similaridade de cossenos o algoritmo sugeriu algumas animações infantis e alguns filmes de besterol americano, mas achei a maioria bem irrelevante. Filmes como 'Shrek' e 'The Hunchback of Notre Dame' não tem absolutamente nada a ver, apesar de serem animações. Utilizando a similaridade de Jaccard algumas das sugestões foram muito boas. 'Aqua Teen Hunger Force Colon Movie Film for Theaters' e 'I Married a Strange Person!' são filmes mais semelhantes do que qualquer um apresentado na lista que utilizou similaridade de cossenos.

Para o caso da franquia escolhi 'Captain America: The First Avenger'. O algoritmo que utiliza similaridade de cosseno traz algumas recomendações bem rankeadas que não são muito condizentes com a entrada oferecida. The 'Helix... Loaded', 'Men in Black II' e 'The Monuments Men' são recomendados antes de 'Guardians of the Galaxy'. Esse último é sugerido pelo algoritmo com similaridade de Jaccard.

In [ ]:
jacc_binary("Beavis and Butt-Head Do America",df)

In [ ]:
recupera_filmes_mais_similar("Beavis and Butt-Head Do America", filmes_similar)

In [ ]:
df[df.title == 'Captain America: The First Avenger']

In [ ]:
jacc_binary("Captain America: The First Avenger",df)

In [ ]:
recupera_filmes_mais_similar("Captain America: The First Avenger", filmes_similar)

## Questão 3

### a)

A maioria das colunas tem relação linear com a primeira. Apenas a observação da coluna 4 linha 2 não segue essa regra para a coluna em que está inserida. Isso não é um problema. Basta inserir mais uma coluna na primeira matriz e mais uma linha na segunda para adicionar a diferença ao valor que queremos obter.

A primeira coluna é um vetor $v_1 = (2,3,5,7)$ que é usado como referência para as outras. Os outros vetores são $v_2 = 5v_1 = (10,15,25,35)$ para a coluna 2, $v_3 = 10v_1 = (20,30,50,70)$ para a coluna 3 e $v5 = 0v_1 = (0,0,0,0)$ para a coluna 5. A coluna 4 é diferente, temos que $v_4 = v_1 + (0,0,27,0)$. Devemos manipular isso nas matriz que geram o resultado.

Escolhemos então $B = 
    \begin{bmatrix} 
	2 & 0\\
	3 & 1 \\
	5 & 0 \\
    7 & 0
    \end{bmatrix}$ e $C = 
    \begin{bmatrix} 
	1 & 5 & 10 & 1 & 0\\
	0 & 0 & 0 & 27 & 0
    \end{bmatrix}$ e iremos obter a matriz $4x5$ de interesse após a multiplicação.

In [ ]:
datafilme = {'col1': [2,3,5,7], 'col2': [10,15,25,35],
                       'col3': [20,30,50,70],'col4': [2,30,5,7],
                       'col5': [0,0,0,0]}
A = pd.DataFrame(datafilme,index=["row1","row2","row3","row4"])
print(A)

In [ ]:
# Bx = A
B = np.array([[2,3,5,7],[0,1,0,0]])
C = np.array([[1,5,10,1,0],[0,0,0,27,0]])
B = B.transpose()

In [ ]:
#Matriz B
B

In [ ]:
#Matriz C
C

In [ ]:
np.dot(B,C) #multiplicação de matrizes

### b)

Aqui temos que a terceira coluna possui uma relação linear com a segunda e a quarta é uma combinação linear entre a primeira e a segunda coluna adicionando mais alguns valores.

A primeira coluna é um vetor $v_1 = (1,4,3)$ e a segunda $v_2 = (5,9,8)$. A terceira coluna é $v_3 = 100v_2 = (5000,9000,8000)$ e a quarta coluna é $v_4 = v_1 + 6v_2 + (0,36,32) = (31,94,83)$.

Escolhemos então $B = 
    \begin{bmatrix} 
	1 & 5 & 0 & 0\\
	4 & 9 & 0 & 36 \\
	3 & 8 & 0 & 32
    \end{bmatrix}$ e $C = 
    \begin{bmatrix} 
	1 & 0 & 0 & 1\\
	0 & 1 & 1000 & 6 \\
    0 & 0 & 0 & 0\\
    0 & 0 & 0 & 1
    \end{bmatrix}$ e iremos obter a matriz $4x4$ de interesse após a multiplicação.

In [ ]:
# Matriz U da preferência em relação a comédia
datafilme = {'col1': [1,4,3], 'col2': [5,9,8],
                       'col3': [5000,9000,8000],'col4': [31,94,83]}
A = pd.DataFrame(datafilme,index=["row1","row2","row3"])
print(A)

In [ ]:
# Bx = A
B = np.array([[1,4,3],[5,9,8],[0,0,0],[0,36,32]])
C = np.array([[1,0,0,0],[0,1,0,0],[0,1000,0,0],[1,6,0,1]])
B = B.transpose()
C = C.transpose()

In [ ]:
#Matriz B
B

In [ ]:
#Matriz C
C

In [ ]:
np.dot(B,C) #multiplicação de matrizes

## Questão 4

Os dois usuários com notas mais semelhantes ao 'User A' são os usuários 'User C' e 'User E'. Podemos utilizar a similaridade de cosseno para descobrir quão similares cada usuários é. Após isso, utilizamos cada valor de similaridade para ponderar as notas conhecidas e fazer uma média entre elas para encontrar uma aproximação para a nota do 'User A'.

Encontramos a nota 4.925 para o filme 'The Hobbit' para o 'User A'. Mantendo o padrão das notas aproximaríamos para 5.

Obs: Essa não é a única abordagem possível. Poderiamos encontrar similaridades entre todos os usuários utilizando as notas disponíveis e fazer a análise a partir delas. Provavelmente conseguiríamos resultados bem diferentes.

In [ ]:
data = {'The Godfather': [5,4,5,1,4], 'Rocky': [3,3,3,1,2], 'The Hobbit':['x',2,5,1,5], 'Fight Club':[1,'y',1,4,1],'Jurassic Park':[4,'y',4,1,5]}  
matrix_resposta = pd.DataFrame(data)
matrix_resposta =matrix_resposta.rename(index={0: "User A", 1: "User B",2:"User C",3:"User D",4:"User E"})
matrix_resposta

In [ ]:
def square_rooted(x):
   return round(sqrt(sum([a*a for a in x])),3)
  
def cosine_similarity(x,y):
 numerator = sum(a*b for a,b in zip(x,y))
 denominator = square_rooted(x)*square_rooted(y)
 return round(numerator/float(denominator),3)
  
print (cosine_similarity([5,3,1,4], [5,3,1,4])) #'User A' x 'User C'
print (cosine_similarity([5,3,1,4], [4,2,1,5])) #'User A' x 'User E'

In [ ]:
#Utilizamos a similaridade como um 'peso' para a nota de cada usuário
nota_hobbit = (1.0*5 + 0.97*5)/2
nota_hobbit

## Questão 5

a) Para a função de similaridade no intervalo (0,1), se sim(x,y) = 1, então x=y. Além disso, o ângulo entre os vetores de informação dos pacientes é de 90º (ortogonal). Portanto, não há correspondência entre os sintomas dos dois (todos os valores são diferentes).

b) O ângulo entre os vetores dos sintomas é de 90º (ortogonal). Portanto, não há dois pacientes com os mesmo sintomas dentre todos os pacientes observados.

c) Se a distância entre os dois pacientes é zero, isso significa que os sintomas são iguais para os dois. Ou seja, se d(x,y) = 0, então x=y.

d) Se a distância entre os dois sintomas é zero, então esses sintomas ocorrem da mesma forma para todos os pacientes (o vetor sintoma_1 e o vetor sintoma_2 são iguais).

Referência: https://www.sciencedirect.com/topics/computer-science/cosine-similarity

## Questão 6

Fazendo $BA = S$, temos que $BA =
    \begin{bmatrix} 
	x1 & y1 & z1 \\
	x2 & y2 & z2 \\
	x3 & y3 & z3 \\
    x4 & y4 & z4 \\
    x5 & y5 & z5
    \end{bmatrix}$ 
    $\begin{bmatrix} 
	1 & 0 & 0 & 0 & 1\\
	0 & 1 & 0 & 1 & 0 \\
	0 & 0 & 1 & 0 & 0
    \end{bmatrix}$
    $ =     \begin{bmatrix} 
	1 & 0 & 1 & 0 & 1 \\
	1 & 0 & 1 & 0 & 1 \\
	1 & 1 & 0.5 & 1 & 1 \\
    0 & 1 & 1 & 1 & 0 \\
    1 & 0 & 0 & 0 & 1
    \end{bmatrix} $.
<br>
Resolvendo esse sistema, encontramos o valor da matriz $B$.
<br>
$B =\begin{bmatrix} 
	1 & 0 & 1 \\
	1 & 0 & 1 \\
	1 & 1 & 0.5 \\
    0 & 1 & 1 \\
    1 & 0 & 0
    \end{bmatrix}$

In [ ]:
dt = {'col1': [1,1,1,0,1], 'col2': [0,0,1,1,0],
                       'col3': [1,1,0.5,1,0],'col4': [0,0,1,1,0],
                       'col5': [1,1,1,0,1]}
sorriso = pd.DataFrame(dt)
sorriso

In [ ]:
from skimage.io import imshow

plt.imshow(sorriso, cmap='gray')
plt.show()

In [ ]:
# Matriz U da preferência em relação a comédia
datafilme = {'row1': [1, 0, 0, 0, 1], 'row2': [0, 1, 0, 1, 0],
                       'row3': [0, 0, 1, 0, 0]}
A = pd.DataFrame(datafilme)
A = A.transpose()

A

In [ ]:
datafilme = {'col1': [1, 0, 1], 'col2': [1, 0, 1],
                       'col3': [1,1,0.5],'col4': [0, 1,1],'col5': [1,0,0]}
B = pd.DataFrame(datafilme)
B = B.transpose()
B

In [ ]:
np.dot(B,A)